# Generated by Django 5.2.7 on 2025-10-09 12:40

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('Full Groom', 'Full Groom'), ('Bath and Tidy', 'Bath and Tidy'), ('The De-shedding Package', 'The De-shedding Package'), ('The Paw Package', 'The Paw Package')], default='Full Groom', max_length=30)),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('time', models.CharField(choices=[('9:00 AM', '9:00 AM'), ('10:30 AM', '10:30 AM'), ('1:00 PM', '1:00 PM'), ('2:30 PM', '2:30 PM'), ('4:00 PM', '4:00 PM'), ('5:30 PM', '5:30 PM')], default='9:00 AM', max_length=10)),
                ('booked_on', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
