# Generated by Django 5.2.7 on 2025-10-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='dog_breed',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='dog_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='Unknown', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
    ]
