# Generated by Django 5.2.7 on 2025-10-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_appointment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='size',
            field=models.CharField(choices=[('Small (under 20 lbs)', 'Small (under 20 lbs)'), ('Medium (20-50 lbs)', 'Medium (20-50 lbs)'), ('Large (50-80 lbs)', 'Large (50-80 lbs)'), ('Giant (over 80 lbs)', 'Giant (over 80 lbs)')], default='Small (under 20 lbs)', max_length=30),
        ),
    ]
