# Generated by Django 5.2.7 on 2025-10-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_appointment_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='dog_name',
            field=models.CharField(max_length=50),
        ),
    ]
