# Generated by Django 5.2.7 on 2025-10-13 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_appointment_dog_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Full Groom', 'Full Groom'), ('Bath and Tidy', 'Bath and Tidy'), ('The De-shedding Package', 'The De-shedding Package'), ('The Paw Package', 'The Paw Package')], max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='size',
            field=models.CharField(choices=[('Small (under 20 lbs)', 'Small (under 20 lbs)'), ('Medium (20-50 lbs)', 'Medium (20-50 lbs)'), ('Large (50-80 lbs)', 'Large (50-80 lbs)'), ('Giant (over 80 lbs)', 'Giant (over 80 lbs)')], max_length=30),
        ),
    ]
