# Generated by Django 5.2.7 on 2025-10-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_appointment_service_alter_appointment_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(blank='False', choices=[('9:00 AM', '9:00 AM'), ('10:30 AM', '10:30 AM'), ('1:00 PM', '1:00 PM'), ('2:30 PM', '2:30 PM'), ('4:00 PM', '4:00 PM'), ('5:30 PM', '5:30 PM')], max_length=10),
        ),
    ]
