# Generated by Django 5.2.7 on 2025-10-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('9:00 AM', '9:00 AM'), ('10:30 AM', '10:30 AM'), ('1:00 PM', '1:00 PM'), ('2:30 PM', '2:30 PM'), ('4:00 PM', '4:00 PM'), ('5:30 PM', '5:30 PM')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('day', 'time')},
        ),
    ]
